"""
MDOAirB

Description:
    - This module calculates the revenue generated by flying a givel O-D pair.

Reference: 
    - Reference: 

TODO's:
    -

| Authors: Alejandro Rios
| Email: aarc.88@gmail.com
| Creation: January 2021
| Last modification: July 2021
| Language  : Python 3.8 or >
| Aeronautical Institute of Technology - Airbus Brazil

"""
# =============================================================================
# IMPORTS
# =============================================================================
import pandas as pd
# =============================================================================
# CLASSES
# =============================================================================

# =============================================================================
# FUNCTIONS
# =============================================================================


# def revenue(demand, distance, pax_capacity, pax_number, average_ticket_price):
#     RPM = pax_number*distance
#     passenger_revenue = pax_number*average_ticket_price
#     yield_ij = passenger_revenue/RPM
#     return demand*distance*yield_ij

def revenue(demand, distance, pax_capacity, pax_number, average_ticket_price):
    """
    Description:
        - Calculates revenue
    Inputs:
        - demand - demand of passengers between O-D pairs
        - distance - distances between O-D pairs
        - pax_capacity - aircraft passenger capacity number
        - pax_number - number of actual passenger transported in O-D leg
        - average_ticket_price - average ticket prince [US$]
    Outputs:
        - revenue - [US$]
    """
    RPM = pax_number*distance
    return demand*average_ticket_price

# =============================================================================
# MAIN
# =============================================================================

# =============================================================================
# TEST
# =============================================================================
# distance = 3000
# load_factor = 0.3
# pax_capacity = 78
# pax_number = 78
# demand = 4000
# print(revenue(demand, distance, pax_capacity, pax_number))
